const fs = require('fs');
const file = 'c:/studio-main/studio-main/src/app/dashboard/my-list/page.tsx';
let code = fs.readFileSync(file, 'utf8');

code = code.replace(/import \{ useUser, useFirestore, useCollection, useMemoFirebase \} from \"@\/firebase\"/, 'import { useUser, useFirestore, useCollection, useDoc, useMemoFirebase } from "@/firebase"');

code = code.replace(/const \[updatingId, setUpdatingId\] = useState<string \\| null>\\(null\\)/, 'const [updatingId, setUpdatingId] = useState<string | null>(null)\n\n  const userProfileRef = useMemoFirebase(() => {\n    if (!db || !user?.uid) return null\n    return doc(db, "users", user.uid)\n  }, [db, user?.uid])\n  const { data: profile } = useDoc(userProfileRef)');

code = code.replace(/const updateData = \{\\s+attendanceStatus: status,\\s+needsRecovery: !isRecovery && status === \"AUSENTE\",\\s+\\.\\.\\.\\(isRecovery && status === \"PRESENTE\" \\? \\{ needsRecovery: false \\} : \\{\\}\\),\\s+lastAttendanceUpdate: serverTimestamp\\(\\)\\s+\\}/, 'const catechistName = profile ? ${profile.firstName}  : (user?.email || "Catequista")\n\n    const updateData = {\n      attendanceStatus: status,\n      needsRecovery: !isRecovery && status === "AUSENTE",\n      ...(isRecovery && status === "PRESENTE" ? { needsRecovery: false } : {}),\n      lastAttendanceUpdate: serverTimestamp(),\n      lastAttendanceTakenBy: catechistName\n    }');

code = code.replace(/<TableHead>Estado<\\/TableHead>\\s+<TableHead className=\"text-right\">Control<\\/TableHead>/, '<TableHead>Estado</TableHead>\n                    <TableHead>Última Asistencia</TableHead>\n                    <TableHead className=\"text-right\">Control</TableHead>');

code = code.replace(/<Badge \\s+variant=\\{conf\\.attendanceStatus === \"PRESENTE\" \\? \"default\" : conf\\.attendanceStatus === \"AUSENTE\" \\? \"destructive\" : \"secondary\"\\}\\s+className=\\{cn\\(conf\\.attendanceStatus === \"PRESENTE\" \\? \"bg-green-500\" : \"\"\\)\\}\\s+>\\s+\\{conf\\.attendanceStatus \\|\\| \"PENDIENTE\"\\}\\s+<\\/Badge>\\s+<\\/TableCell>/, '<Badge \n                          variant={conf.attendanceStatus === "PRESENTE" ? "default" : conf.attendanceStatus === "AUSENTE" ? "destructive" : "secondary"}\n                          className={cn(conf.attendanceStatus === "PRESENTE" ? "bg-green-500" : "")}\n                        >\n                          {conf.attendanceStatus || "PENDIENTE"}\n                        </Badge>\n                      </TableCell>\n                      <TableCell>\n                        {conf.lastAttendanceUpdate ? (\n                           <div className=\"flex flex-col\">\n                             <span className=\"text-xs font-bold text-slate-700\">\n                               {conf.lastAttendanceUpdate?.toDate ? conf.lastAttendanceUpdate.toDate().toLocaleDateString(\\'es-PY\\', { day: \\'2-digit\\', month: \\'short\\', hour: \\'2-digit\\', minute: \\'2-digit\\' }) : \"Reciente\"}\n                             </span>\n                             <span className=\"text-[10px] text-slate-400 capitalize\">Por: {conf.lastAttendanceTakenBy?.toLowerCase() || \"Desconocido\"}</span>\n                           </div>\n                        ) : (\n                           <span className=\"text-xs text-slate-400 italic\">No registrada</span>\n                        )}\n                      </TableCell>');

code = code.replace(/<TableHead>Día Original<\\/TableHead>\\s+<TableHead className=\"text-right\">Control<\\/TableHead>/, '<TableHead>Día Original</TableHead>\n                    <TableHead>Última Asistencia</TableHead>\n                    <TableHead className=\"text-right\">Control</TableHead>');

code = code.replace(/<Badge variant=\"outline\" className=\"text-\\[10px\\] uppercase\">\\{conf\\.attendanceDay\\}<\\/Badge>\\s+<\\/TableCell>/, '<Badge variant=\"outline\" className=\"text-[10px] uppercase\">{conf.attendanceDay}</Badge>\n                      </TableCell>\n                      <TableCell>\n                        {conf.lastAttendanceUpdate ? (\n                           <div className=\"flex flex-col\">\n                             <span className=\"text-xs font-bold text-slate-700\">\n                               {conf.lastAttendanceUpdate?.toDate ? conf.lastAttendanceUpdate.toDate().toLocaleDateString(\\'es-PY\\', { day: \\'2-digit\\', month: \\'short\\', hour: \\'2-digit\\', minute: \\'2-digit\\' }) : \"Reciente\"}\n                             </span>\n                             <span className=\"text-[10px] text-slate-400 capitalize\">Por: {conf.lastAttendanceTakenBy?.toLowerCase() || \"Desconocido\"}</span>\n                           </div>\n                        ) : (\n                           <span className=\"text-xs text-slate-400 italic\">No registrada</span>\n                        )}\n                      </TableCell>');

fs.writeFileSync(file, code, 'utf8');
